## 00. Python Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Introductions to Tensors

## Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python int

scaler.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers`

Torch random numbers -> https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4767, 0.5754, 0.6695, 0.3943],
        [0.9280, 0.1584, 0.8933, 0.1375],
        [0.2902, 0.9849, 0.5454, 0.1512]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor[0]

tensor([0.4767, 0.5754, 0.6695, 0.3943])

In [ ]:
torch.rand(2,3,4)

tensor([[[0.7995, 0.3990, 0.4995, 0.7639],
         [0.5582, 0.9351, 0.6252, 0.5983],
         [0.9501, 0.4661, 0.0541, 0.3578]],

        [[0.4715, 0.5453, 0.6710, 0.1877],
         [0.6075, 0.4486, 0.0299, 0.9344],
         [0.6397, 0.6397, 0.4832, 0.7265]]])

The tensor can be used to represent an image as shown below

The tesor `[224, 224, 3]` represents `[height, width, color_channel]`

In [ ]:
# Create a random tensor similar to a shape of random tensor

random_image_size_tensor = torch.rand(size = (224,224, 3)) # height, width and colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Tensor datatypes

**Note:** Tensor datatypes are going to be one of the 3 big errors we will be running into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

**Precision in computing** - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None)

float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)

float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
### 3 most important parameters for tensors

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float16 or float32)
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor* float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
(int_32_tensor*float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Tensor datatypes - to do get `tensor.dtype`
2. Tensor shape - to do get `tensor.shape`
3. Tensor device - to do get `tensor.device`

In [ ]:
# Creating a tensor

some_tensor = torch.rand(4,3)
some_tensor

tensor([[0.4975, 0.8348, 0.5500],
        [0.1106, 0.5524, 0.7537],
        [0.7954, 0.8356, 0.8434],
        [0.8841, 0.6078, 0.9237]])

In [ ]:
# Find info on tensor (Tensor attributes)

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([4, 3]), device(type='cpu'))

### Manipulating tensors (Tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [ ]:
# Create a tensor and adding 10 to it

tensor = torch.tensor([1,2,3])
tensor = tensor + 10

In [ ]:
tensor

tensor([11, 12, 13])

In [ ]:
# Create a tensor and subtracting 10 from it

tensor = torch.tensor([1,2,3])
tensor = tensor - 10

tensor

tensor([-9, -8, -7])

In [ ]:
# Create a tensor and multiplying 10 to it

tensor = torch.tensor([1,2,3])
tensor = tensor * 10

tensor

tensor([10, 20, 30])

In [ ]:
# Create a tensor and dividing it by 10

tensor = torch.tensor([1,2,3])
tensor = tensor / 10

tensor

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways to perform matrix multiplication in PyTorch and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are 2 main rules matrix multiplication must satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [ ]:
# element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([0.1000, 0.2000, 0.3000]) * tensor([0.1000, 0.2000, 0.3000])
Equals: tensor([0.0100, 0.0400, 0.0900])


In [ ]:
### Matrix multiplication

torch.matmul(tensor, tensor)

tensor(0.1400)

In [ ]:


### Time analysis of built-in function and a for loop for matrix multiplication
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(0.1400)
CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.64 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 310 µs, sys: 0 ns, total: 310 µs
Wall time: 275 µs


tensor(0.1400)

### One of the most common errors of deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix the tensor shape errors we can use **transpose** of a matrix

In [ ]:
tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.matmul(tensor_B.T, tensor_A)

tensor([[35, 44],
        [44, 56]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
### One of the major PyTorch errors, wrong dtype

torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
### To find the position of the minimum value
x.argmin() ## index value

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
### To find the position of the max value

x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes the input tensor in the defined shape

* **View** - return a view of an input tensor of certain shape but keep the same memory as the original

* **Stack** - combining tensors `v-stack` or `h-stack`

* **Squeeze**- removes all `1` dimensions from the tensor

* **Unsqueeze** - add `1` dimension to a target tensor

* **Permute** - return a view of the tensor `permuted` (swapped) in a certain manner

The crux of all this is that all these operations are done to change the shapes of the tensor

### Reshaping tensor

In [ ]:
# Let's create a tensor
import torch as t
x = t.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.reshape(9,1), x.reshape(9,1).shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x.reshape(3,3), x.reshape(3,3).shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

# Change the view


In [ ]:
z = x.view(3,3)
z, z.shape, x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
z[:,0] = 5 ### Changing z changes x (view shares the same memory as the original tensor)
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

# Stacking tensors

In [ ]:
x_stacked = t.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
x_stacked = t.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# Squeeze tensor

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape ## remove the extra dimensions

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x_reshaped.squeeze()
x_reshaped.shape

torch.Size([9])

In [ ]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 9])

# Permuting the tensor

* Rearranging the dimensions of tensor in a specified manner

* Permute shares the same memory as the original tensor

In [ ]:
x_original = t.rand(size=(224,223,3)) # [height, width, color channel]]

In [ ]:
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 1->2 2->0

In [ ]:
x_permuted.shape # [color_channel, height, width]

torch.Size([3, 224, 223])

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor

import torch as t

x = t.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0], x[0].shape # Index by first dimension

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
x[0,0] # Index by second dimension

tensor([1, 2, 3])

In [ ]:
x[0][0][0] # index by third dimension

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# you can use ':' to select all of a target dimension

x[:, 0], x[:,0].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [ ]:
# Get all the value of the 0th index and let 1st dimension but only index 2 of the second dimension

x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
x[0,1,:]

tensor([4, 5, 6])

## PyTorch tensors and NumPy

NumPy is a python numerical computing library

Pytorch has a fuctionality to interact with it

* Data in numpy and to turn it into tensor -> `torch.from_numpy(array)`

In [ ]:
# while converting numpy to tensor it converts to float64 unless specified
# it can cause datatype errors

import numpy as np

array = np.arange(1.0, 8.0)
tensor = t.from_numpy(array).type(t.float32)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
# Change the value of array

array = array + 1
array, tensor

# It does not change the value of the tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to numpy array

tensor = t.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

# Tensor to array; default dtype is float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

How a neural network works:

`start with random numbers -> tensor operations -> update random numbers to try and make them look like a better representation of the data -> repeat the procees till loss function is virtually minimum`

To reduce the randomness in neurak network and pytorch comes a concept of **random seed**

Essentially what the random seed is 'flavor' the randomness

In [ ]:
import torch as t


# Create randome tensors


random_tensor_A = t.rand(3,4)
random_tensor_B = t.rand(3,4)

random_tensor_A, random_tensor_B

(tensor([[0.4732, 0.8345, 0.6697, 0.9573],
         [0.1498, 0.0171, 0.6679, 0.8674],
         [0.2852, 0.2259, 0.7163, 0.5501]]),
 tensor([[0.5645, 0.2297, 0.0729, 0.3199],
         [0.7350, 0.6597, 0.8583, 0.3006],
         [0.9459, 0.9795, 0.5461, 0.1956]]))

In [ ]:
# Creating random reproducible tensors
import torch as t

# Setting random seed
random_seed = 42

t.manual_seed(random_seed)

random_tensor_C = t.rand(3,4)

random_tensor_D = t.rand(3,4)

random_tensor_C, random_tensor_D


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

### Reproducibility read more:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random

# Running tensors and pytorch object on GPUs

* GPUs do faster computation on numbers using CUDA and NVIDIA hardware

# 1. Getting a GPU

* Easiest - UJse a Colab for a free GPU (there are paid options)
* Using one's own GPU
* Use cloud computing - GCP, AWS, Azure etc. These services allow you to rent computers on the cloud and access them

For own GPU usage, PyTorch + GPU drivers (CUDA) will be needed. All the needed info can be found:
https://pytorch.org/get-started/locally/


Further readings for a good GPU for deep learning : https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/



In [ ]:
!nvidia-smi

Fri Dec 20 07:41:24 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

###2. Check for GPU access for PyTorch

In [ ]:
import torch as t
t.cuda.is_available()

True

# Setup device agnostic code

When the code runs on a diiferent system if GPU is available then use it.

For pytorch since it is capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

Ex: Run on GPU if available, else default run on CPU

In [ ]:
device = "cuda" if t.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices

t.cuda.device_count()

1

# Putting tensors/models on GPU

* The reason to run tensors/models on GPU is that they are faster in numerical calculation in comparison with CPUs

In [ ]:
# Create a tensor

tensor = t.tensor([1,2,3])

# Tensor not on GPU

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensors back to CPUs
* If tensor is on GPU it can't be transformed to NumPy

*  To convert tensor_on_gpu to a numpy array, it has to be put on the CPU first. NumPy does not work with GPUs

In [ ]:
# tensor_on_gpu.numpy() , this code will give 'on wrong devive error'

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_back_on_cpu, tensor_on_gpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

## Exercises and Extra-curriculum

In [5]:
# Creating random tensor
import torch as t

tensor = t.rand(7,7).reshape(1,7,7)
tensor, tensor.shape

(tensor([[[0.3283, 0.3515, 0.9129, 0.3802, 0.2163, 0.2540, 0.5099],
          [0.7144, 0.4675, 0.8725, 0.4252, 0.2594, 0.9518, 0.3496],
          [0.2219, 0.1436, 0.2922, 0.7952, 0.8537, 0.8981, 0.3697],
          [0.2284, 0.2720, 0.2478, 0.6597, 0.2260, 0.2583, 0.4151],
          [0.4414, 0.2904, 0.3647, 0.5012, 0.3132, 0.0652, 0.3321],
          [0.8624, 0.6510, 0.1696, 0.1736, 0.8610, 0.0280, 0.9077],
          [0.7899, 0.7544, 0.0966, 0.0738, 0.5154, 0.1904, 0.4355]]]),
 torch.Size([1, 7, 7]))

In [6]:
# Multiplying two tensors

tensor_A = t.rand(1,7)
tensor_B = t.rand(1,7)

tensor_A, tensor_B

(tensor([[0.5756, 0.2307, 0.0360, 0.7253, 0.8897, 0.1657, 0.6405]]),
 tensor([[0.5426, 0.3370, 0.6216, 0.1461, 0.6308, 0.6825, 0.8742]]))

In [7]:
tensor_C = t.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[1.7527]]), torch.Size([1, 1]))

In [6]:
### performing above exercises with random seed
import torch as t
seed = 0

t.manual_seed(seed)

tensor = t.rand(7,7)

tensor_A = t.rand(1,7)
tensor_B = t.rand(1,7)

tensor_C = t.matmul(tensor_A, tensor_B.T)
tensor, tensor_C

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[1.7395]]))

In [5]:
# setting seed on gpu
import torch as t

device = "cuda" if t.cuda.is_available() else "cpu"

t.cuda.manual_seed(1234)

tensor_A = t.rand(size=(3,3)).to(device)

tensor_A,

(tensor([[0.3315, 0.7837, 0.5631],
         [0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]], device='cuda:0'),)

In [7]:
t.manual_seed(1234)

tensor_B = t.rand(2,3).to(device)

tensor_C = t.rand(2,3).to(device)

tensor_B, tensor_C

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [10]:
tensor_D = t.matmul(tensor_B, tensor_C.T)
tensor_D

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [13]:
t.max(tensor_D), t.min(tensor_D)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [17]:
# some tensor operations

t.cuda.manual_seed(7)

tensor_E = t.rand(1,1,1,10)
tensor_F = tensor_E.reshape(10)

print(tensor_F, tensor_F.shape)

print(tensor_E, tensor_E.shape)

tensor([0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839, 0.8083, 0.7528,
        0.8988]) torch.Size([10])
tensor([[[[0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839, 0.8083,
           0.7528, 0.8988]]]]) torch.Size([1, 1, 1, 10])
